version: "3.3"

services:
  web:
    build: .
    # command: service cron start
    command: /code/dashboard_site/manage.py runserver 0.0.0.0:8000
    # command: /usr/sbin/service cron start; /code/dashboard_site/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: